language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
 - sudo apt-get install nuget
 - sudo nuget install Docker.DotNet
script:
 - dotnet restore DNCinDocker.sln
 - dotnet build DNCinDocker.sln