version: '2'

services:
  dncindocker:
    image: matoba/dncindocker:ci
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    links:
      - proxy:webapp
  proxy:
    image: matoba/dncproxy:ci
    ports:
     - "443:443"