version: '2'

services:
  dncindocker:
    image: matoba/dncindocker:ci
    ports:
     - "8080:80"
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    links:
      - dncindocker:webapp