version: '2'

services:
  dncindocker:
    build:
      context: ./DNCinDocker
      dockerfile: Dockerfile
    image: matoba/dncindocker:ci
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    links:
      - proxy:webapp
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: matoba/dncproxy:ci
    ports:
      - "443:443"
    links:
      - dncindocker:app
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
