version: '2'

services:
  dncindocker:
    image: matoba/dncindocker:latest
    ports:
      - '80:80'
  cdcc:
    image: matoba/cdcc
    ports:
      - '80:80'
      - '443:443'
    links:
      - dncindocker:apocalypse
    volumes: 
      - cdcc:/etc/letsencrypt
    environment:
      DOMAIN: '${HOST_NAME}'
      E_MAIL: '${MAIL}'
      LINK_NAME: 'apocalypse'
    fip: ${HYPER_IP}
    size: s3